大一小学期/Week_3-Python/exam/2016/2015011334_week3/3/mysite/mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^', include('searchengine.urls')),
#    url(r'^admin/', admin.site.urls),
]

大一小学期/Week_3-Python/exam/2016/2015011334_week3/3/mysite/searchengine/urls.py
from django.conf.urls import url
from . import views

app_name = 'searchengine'
urlpatterns = [
#    url(r'^$', views.index, name='index'),
    url(r'^search/$', views.search, name='search'),
#    url(r'^search/(?P<words>.+?)/(?P<page_id>[0-9]+)/$', views.result, name='result'),
#    url(r'^(?P<question_id>[0-9]+)/$', views.detail, name='detail'),
#    url(r'^(?P<question_id>[0-9]+)/results/$', views.results, name='results'),
#    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
]

大一小学期/Week_3-Python/exam/2016/2015011334_week3/3/mysite/searchengine/models.py
from __future__ import unicode_literals

from django.db import models
from django.utils.encoding import python_2_unicode_compatible

# Create your models here.

@python_2_unicode_compatible
class Event(models.Model):
    event = models.CharField(max_length=200)
    ttime = models.CharField(max_length=200)
    def __str__(self):
        return self.event

大一小学期/Week_3-Python/exam/2016/2015011334_week3/3/mysite/searchengine/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.urls import reverse
from .models import Event
import jieba

def search(request):
    if request.POST.has_key('add'):
        event = request.POST['event']
        ttime = request.POST['ttime']
        Event.objects.create(event=event, ttime=ttime)
        return render(request, 'searchengine/search.html', {'events': None})
    elif request.POST.has_key('query'):
        event = request.POST['event']
        ttime = request.POST['ttime']
        if event:
            result = Event.objects.filter(event=event)
        else:
            result = Event.objects
        if ttime:
            result = result.filter(ttime=ttime)
        else:
            result = result
        return render(request, 'searchengine/search.html', {'events': result.all()})
    else:
        id = -1
        for i in range(1000):
            if request.POST.has_key('del'+str(i)):
                Event.objects.filter(id=i).delete()
                break
    return render(request, 'searchengine/search.html', {'events': None})

大一小学期/Week_3-Python/exam/2016/2015011334_week3/3/mysite/searchengine/templates/searchengine/base.html
{% load static %}
<html>
    <head>
        <title>学校搜索引擎</title>
        <meta charset="utf-8">
    </head>
    <body>
        <div>
            <form action="{% url 'searchengine:search' %}" method="post" class="form">
                {% csrf_token %}
                <input type="text" name="event" id="event">
                <label for="event">事件</label><br>
                <input type="datetime-local" name="ttime" id="ttime">
                <label for="ttime">时间</label><br>
                <button type="submit" name="add" class="btn btn-primary">添加事件</button>
                <button type="submit" name="query" class="btn btn-primary">查询事件</button>
                <button type="submit" name="rewrite" class="btn btn-primary">重写</button>
            </form>
        </div>
        {% block content %}
        {% endblock %}
    </body>
</html>

大一小学期/Week_3-Python/exam/2016/2015011334_week3/3/mysite/searchengine/templates/searchengine/search.html
{% extends 'searchengine/base.html' %}
{% block content %}
<div>
    {% for event in events %}
        {{ event.event }}|||{{ event.ttime }}|||
        <form action="{% url 'searchengine:search' %}" method="post" class="form">
            {% csrf_token %}
            <button type="submit" name="del{{ event.id }}" class="btn btn-primary">删除</button>
        </form><br>
    {% endfor %}
</div>
{% endblock content %}